
language:
  - cpp

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo `cmake -version
 sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.7
 packages:
  - gcc-4.9
  - g++-4.9
  - clang-3.7
  - valgrind

compiler:
  - g++

env:
  - GTEST_TARGET=googletest SHARED_LIB=OFF STATIC_LIB=ON CMAKE_PKG=OFF BUILD_TYPE=debug  VERBOSE_MAKE=true VERBOSE
  - CXX_FLAGS=''

script: ./.travis.sh

git:
  only:
  - lab6

notifications:
 email: false
