language: 
 - cpp

install:
 sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-precise-3.7
 packages:
  - gcc-4.9
  - g++-4.9
  - clang-3.7
  - valgrind

compiler:
 - g++

env:
  matrix:
    - GTEST_TARGET=googletest SHARED_LIB=OFF STATIC_LIB=ON CMAKE_PKG=OFF BUILD_TYPE=debug  VERBOSE_MAKE=true VERBOSE


script: ./.travis.sh


notifications:
 email: false
